name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose up -d --build
          docker compose ps

      - name: Run QR code generator (example command)
        run: |
          docker compose exec -T qr_code_app python main.py --url https://github.com/kennyasare7/IS601_Assignment7

      - name: Stop and clean up
        if: always()
        run: docker compose down